/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pwr_ite_dynak_filters_MedianFilter */

#ifndef _Included_pl_pwr_ite_dynak_filters_MedianFilter
#define _Included_pl_pwr_ite_dynak_filters_MedianFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pwr_ite_dynak_filters_MedianFilter
 * Method:    applyFilterNative
 * Signature: ([IIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_pl_pwr_ite_dynak_filters_MedianFilter_applyFilterNative
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
