spring.application.name=lab06
spring.datasource.url=jdbc:sqlite:mydatabase.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.devtools.restart.enabled=false
#spring.jpa.show-sql=true
logging.file.name=logs/app.log

springdoc.swagger-ui.path=/v3/api-docs