/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pwr_ite_dynak_filters_GaussianFilter */

#ifndef _Included_pl_pwr_ite_dynak_filters_GaussianFilter
#define _Included_pl_pwr_ite_dynak_filters_GaussianFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pwr_ite_dynak_filters_GaussianFilter
 * Method:    applyFilterNative
 * Signature: ([IIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_pl_pwr_ite_dynak_filters_GaussianFilter_applyFilterNative
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
